### ISSUE TITLE
Readme.md file should include starting links to connect out to other docs

### ISSUE THREAD

**Issue by science** [K12OCX/k12ocx-specs#1]
The main readme file should have links and table of contents like structure to help give a "default view" of all the content pages. Where content pages aren't directly linked from the Readme, they should be linked from a page that is linked in the readme. Basically eliminate all orphan pages..

Maybe the markdown generator already does this, but it still seems important to have all the content linked in the repo, in addition to whatever the generator creates?

**Comment by andersoncardoso** [comment]
added here: https://github.com/K12OCX/k12ocx-specs/commit/a7fe28e7a4fe1cc2441d29e144fc1eae062c5ba9
