### ISSUE TITLE
Add License info

### ISSUE THREAD

**Issue by andersoncardoso** [K12OCX/k12ocx-specs#2]
Not sure which license we should use.

**Comment by philbarker** [comment]
Draft K-12 OCX Community Group Charter says "All materials will be contributed under two licenses: Apache 2 and CC-BY-4. This means that any contribution can be used under either license."

**Comment by philbarker** [comment]
Checked with Steve and Joe on call today and decided to simplify by dropping CC:By for now. Apache 2 has us covered for what CC:By would allow
